apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: album-service
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: album-service
            version: 0.2.4
            # chartPath: ./install/helm/album-service # comment out repoChart and repo to use local version
            remoteChart: album-service
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: album-service
            createNamespace: true
            valuesFiles: ["./install/values/k3d/album-service.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: proxy-service
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: proxy-service
            version: 0.2.4
            # chartPath: ./install/helm/proxy-service # comment out repoChart and repo to use local version
            remoteChart: proxy-service
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: proxy-service
            createNamespace: true
            valuesFiles: ["./install/values/k3d/proxy-service.values.yaml"]
