apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: prometheus
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: prometheus
            remoteChart: prometheus
            version: 20.2.0
            repo: https://prometheus-community.github.io/helm-charts
            namespace: monitoring
            createNamespace: true
            wait: true
            valuesFiles: ["./install/values/microk8s/prometheus.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: istio
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: istio-base
            remoteChart: base
            version: 1.17.2
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/istio-base.values.yaml"]
          - name: istiod
            remoteChart: istiod
            version: 1.17.2
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            wait: true # have to wait so ready when gateway asks for istiod
            valuesFiles: ["./install/values/microk8s/istio-istiod.values.yaml"]
          - name: istio-ingressgateway
            remoteChart: gateway
            version: 1.17.2
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            setValueTemplates:
              service.externalIPs[0]: "{{.ISTIO_GATEWAY_EXTERNAL_IP}}"
            valuesFiles: ["./install/values/microk8s/istio-gateway.values.yaml"]
          - name: kiali
            remoteChart: kiali-server
            version: 1.68.0
            repo: https://kiali.org/helm-charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/kiali-server.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: grafana-dashboards
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: grafana-dashboards
            # chartPath: ./install/helm/grafana-dashboards # comment out repoChart and repo to use local version
            remoteChart: grafana-dashboards
            version: 1.0.7
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: monitoring
            createNamespace: true
            valuesFiles:
              ["./install/values/microk8s/grafana-dashboards.values.yaml"]
            wait: true
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: grafana
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: grafana
            remoteChart: grafana
            version: 6.56.5
            repo: https://grafana.github.io/helm-charts
            namespace: monitoring
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/grafana.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: jaeger
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: jaeger-all-in-one
            remoteChart: jaeger-all-in-one
            version: 0.1.8
            repo: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts
            namespace: observability
            createNamespace: true
            valuesFiles:
              ["./install/values/microk8s/jaeger-all-in-one.values.yaml"]
            wait: true # needed when otel-collector sends data to jaeger but not currently.
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: opentelemetry-collector-microk8s
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: opentelemetry-collector
            remoteChart: opentelemetry-collector
            version: 0.53.0
            repo: https://open-telemetry.github.io/opentelemetry-helm-charts
            namespace: observability
            createNamespace: true
            valuesFiles:
              ["./install/values/microk8s/opentelemetry-collector.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: dashboard
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: kubernetes-dashboard
            remoteChart: kubernetes-dashboard
            version: 6.0.6
            repo: https://kubernetes.github.io/dashboard/
            namespace: kubernetes-dashboard
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/dashboard.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: istio-ingresses
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: istio-ingress-charts
            version: 0.1.5
            # chartPath: ./install/helm/istio-ingress-charts # comment out repoChart and repo to use local version
            remoteChart: istio-ingress-charts
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: default
            valuesFiles: ["./install/values/microk8s/istio-ingress.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: album-service
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: album-service
            # chartPath: ./install/helm/album-service # comment out repoChart and repo to use local version
            version: 0.2.4
            remoteChart: album-service
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: album-service
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/album-service.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: proxy-service
profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      helm:
        releases:
          - name: proxy-service
            # chartPath: ./install/helm/proxy-service # comment out repoChart and repo to use local version
            version: 0.2.4
            remoteChart: proxy-service
            repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: proxy-service
            createNamespace: true
            valuesFiles: ["./install/values/microk8s/proxy-service.values.yaml"]
